services:
  backend:
    image: omi-backend
    build:
      context: .
    container_name: omi-backend
    ports:
      - "8000:8000"
    env_file:
      - .dev.env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - LD_LIBRARY_PATH=/usr/local/lib
      - LIBRARY_PATH=/usr/local/lib
